Repository gammacommunications/vue-svg-loader-2, pull requests merged in 2022-09, with the labels that each got.

#1 Create dependabot.yml
  .github/dependabot.yml
Labels: config

#6 updated packages and increased version
  package-lock.json
  package.json
  yarn.lock
Labels: config

#8 fix: fix template creation, provide sensible defaults to SVGO
  index.js
  package-lock.json
  package.json
  yarn.lock
Labels: bug, enhancement

#10 Chore/prepare publish 0.17.0 beta 3
  .npmignore
  package-lock.json
  package.json
  yarn.lock
Labels: config, npm, dependencies

#11 Chore/prepare publish 0.17.0 beta 3
  package.json
Labels: config, npm
