Repository gammacommunications/vue-svg-loader-2, pull requests merged in 2023-06, with the labels that each got.

#87 chore: version 0.17.0
  .github/dependabot.yml
  .github/workflows/node.js.yml
  .gitignore
  .npmignore
  LICENSE
  README.md
  babel.config.js
  docs/.vuepress/Example.vue
  docs/.vuepress/config.js
  docs/.vuepress/enhanceApp.js
  docs/.vuepress/public/logo.svg
  docs/.vuepress/public/svgo.svg
  docs/.vuepress/public/vue.svg
  docs/.vuepress/public/webpack.svg
  docs/.vuepress/styles/index.styl
  docs/README.md
  docs/faq.md
  index.js
  package-lock.json
  package.json
  svgoConfigBuilder.js
  test/compiler.js
  test/configBuilder.test.js
  test/dummyLoader.js
  test/loader.test.js
  test/test.svg
  yarn.lock
Labels: enhancement, config, dependencies

#90 merge dev in main
  README.md
Labels: documentation

#92 chore: update package version to 0.17.1
  package.json
Labels: config
